# Generated by Django 5.2.1 on 2025-06-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_type',
            name='refresh_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
