# Generated by Django 5.2.1 on 2025-05-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ping_view',
                'verbose_name_plural': 'ping_view',
                'db_table': 'app_name_ping_view',
            },
        ),
    ]
