# Generated by Django 5.2.1 on 2025-05-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0003_domainlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'check_http_view',
                'verbose_name_plural': 'check_http_views',
                'db_table': 'app_name_check_http_view',
            },
        ),
    ]
