# Generated by Django 5.2.1 on 2025-05-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0009_nsclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinglog',
            old_name='host',
            new_name='ping_host',
        ),
        migrations.RenameField(
            model_name='printclass',
            old_name='name',
            new_name='user_name',
        ),
    ]
