# Generated by Django 5.2.1 on 2025-05-24 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0010_rename_host_pinglog_ping_host_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainlog',
            old_name='domain',
            new_name='ssl_domain',
        ),
    ]
