# Generated by Django 5.2.1 on 2025-05-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0011_rename_domain_domainlog_ssl_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='httplog',
            old_name='domain',
            new_name='securityheaders_domain',
        ),
    ]
