# Generated by Django 5.2.1 on 2025-05-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0012_rename_domain_httplog_securityheaders_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checksslclass',
            old_name='domain',
            new_name='cloudflare_domain',
        ),
    ]
