# Generated by Django 5.2.1 on 2025-05-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0013_rename_domain_checksslclass_cloudflare_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checksslclass',
            old_name='cloudflare_domain',
            new_name='ssllabs_domain',
        ),
        migrations.RenameField(
            model_name='cloudclass',
            old_name='domain',
            new_name='cloudflare_domain',
        ),
        migrations.RenameField(
            model_name='nsclass',
            old_name='domain',
            new_name='ns_lookup_domain',
        ),
    ]
